### ISSUE TITLE
Introducing two papers on (1) role-playing LLM agents & (2) persona-grounded conversational agents

### ISSUE THREAD

**Issue by ahnjaewoo** [Sahandfer/PersonaPaper#2]
Hi, what a fantastic resource for developing Persona-based conversational agents!

I want to highlight a recent paper presented at ACL 2024 Findings: [TimeChara: Evaluating Point-in-Time Character Hallucination of Role-Playing Large Language Models](https://ahnjaewoo.github.io/timechara).
This study focuses on _assessing hallucinations_ in role-playing LLM agents when they simulate **characters at specific moments in time**.

In addition, I want to introduce another paper presented at ACL 2023 Main: [MPCHAT: Towards Multimodal Persona-Grounded Conversation](https://aclanthology.org/2023.acl-long.189/).
This study focuses on constructing a **multimodal persona-grounded dialogue dataset**, where a multimodal (i.e., text+image) persona represents the _user's personal experiences in their episodic memories_.

We would greatly appreciate it if you could consider adding our papers to your repository and your survey paper.
Thanks!

**Comment by Sahandfer** [comment]
Thank you for sharing and congratulations on your work! I will add them in the next commit.
